In [4]:
#Importing packages
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("orders.csv")
df = pd.DataFrame(data)
df

OrderID  CustomerID  Amount   OrderDate
0      101         1.0  250.50  2024-12-20
1      102         2.0  120.00  2024-12-21
2      103         3.0  320.00  2024-12-22
3      104         4.0     NaN  2024-12-23
4      105         NaN  150.75  2024-12-24

In [8]:
#Filling missing values
df["CustomerID"] = df["CustomerID"].bfill()
df

OrderID  CustomerID  Amount   OrderDate
0      101         1.0  250.50  2024-12-20
1      102         2.0  120.00  2024-12-21
2      103         3.0  320.00  2024-12-22
3      104         4.0     NaN  2024-12-23
4      105         4.0  150.75  2024-12-24

In [14]:
new_df=df.interpolate()
new_df

<ipython-input-14-dfbaf556cf83>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df=df.interpolate()


OrderID  CustomerID   Amount   OrderDate
0      101         1.0  250.500  2024-12-20
1      102         2.0  120.000  2024-12-21
2      103         3.0  320.000  2024-12-22
3      104         4.0  235.375  2024-12-23
4      105         4.0  150.750  2024-12-24

In [15]:
df.describe()

OrderID  CustomerID      Amount
count    5.000000     5.00000    5.000000
mean   103.000000     2.80000  215.325000
std      1.581139     1.30384   80.394224
min    101.000000     1.00000  120.000000
25%    102.000000     2.00000  150.750000
50%    103.000000     3.00000  235.375000
75%    104.000000     4.00000  250.500000
max    105.000000     4.00000  320.000000

In [16]:
df["CustomerID"].value_counts() #Counts unique values in the column CustomerID

CustomerID
4.0    2
1.0    1
2.0    1
3.0    1
Name: count, dtype: int64

In [25]:
orders_df =df[["OrderID","Amount"]]
orders_df

OrderID   Amount
0      101  250.500
1      102  120.000
2      103  320.000
3      104  235.375
4      105  150.750

In [24]:
orders_df["Amount"]=orders_df["Amount"].apply(lambda x : x + 50)
orders_df

<ipython-input-24-05e37c86839f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_df["Amount"]=orders_df["Amount"].apply(lambda x : x + 50)


OrderID   Amount
0      101  300.500
1      102  170.000
2      103  370.000
3      104  285.375
4      105  200.750

In [26]:
arr = orders_df["Amount"].to_numpy()
arr

array([250.5  , 120.   , 320.   , 235.375, 150.75 ])

In [30]:
arr.dtype

dtype('float64')

In [35]:
np.vstack(arr)
# Creates a vertical stack

array([[250.5  ],
       [120.   ],
       [320.   ],
       [235.375],
       [150.75 ]])

In [34]:
np.hstack(arr) #creates a horizontal stack

array([250.5  , 120.   , 320.   , 235.375, 150.75 ])

In [36]:
np.sort(arr)

array([120.   , 150.75 , 235.375, 250.5  , 320.   ])

In [37]:
np.unique(arr)

array([120.   , 150.75 , 235.375, 250.5  , 320.   ])

In [39]:
arr[np.where(arr < 200)]

array([120.  , 150.75])

In [41]:
#Max and min elements
arr[np.argmax(arr)]

320.0

In [42]:
arr[np.argmin(arr)]

120.0